apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 3-tier-app-eks
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hendawyy/frontendsql:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: backend-url
              key: BACKEND_URL
